### ISSUE TITLE
White screen in SFOS 2.2.1.18

### ISSUE THREAD

**Issue by lfc22src** [direc85/harbour-themetool#5]
Upon opening app in 2.2.1.18 a white screen is only shown.
[themetool.2.2.1.18.log](https://github.com/direc85/harbour-themetool/files/3892705/themetool.2.2.1.18.log)

**Comment by direc85** [comment]
This says it all: `qml/components/ThemeIcon.qml:29:5: Icon is not a type`

I managed to locate previous versions of Sailfish SDKs, and I'm downloading 2.2.1.18 - the in the 2.x series actually - so I can try and develop a fix for it.

**Comment by direc85** [comment]
It was a bit cumbersome to bug hunt simultaneously on two SDKs on different computers, but fixed version has been released. Could you test the new version and see if it works? I don't have an actual device with SFOS 2 right now, but it works in the emulator just fine.

**Comment by lfc22src** [comment]
Thanks for the fix. It is working now.
